### ISSUE TITLE
Puppet run doesn't work via WebUI

### ISSUE THREAD

**Issue by linuxbsdfreak** [kermitfr/kermit-webui#5]
Hi,

I chked that invoking puppet runs via the WebUI doesnt work. I just gives an output

Output: Called /usr/bin/puppetd --onetime --splaylimit 50 --splay, Currently idling; last completed run 2179 seconds ago 

Also on the system there is no binary named puppetd. puppet agent is normally used for puppet runs.

Please have a look at the earliest.

**Comment by mmornati** [comment]
I need more info to checkout this bug. What is the puppet agent used to run this operation?

**Comment by mmornati** [comment]
As discussed, it's an mcollective agent problem (custom agent) and not directly impacted by the Kermit Framework
